import type { NextPage } from "next";
import React from "react"
import Head from "next/head";
import Layout from "../components/Layout";
import { Splash } from "../components/Splash";
import { Container } from "../components/base";

const Home: NextPage = () => {
  return (
    <Layout size={4}>
      <Head>
        <title>Bryan Paronto | Software Engineer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container size={4}>
        <Splash />
      </Container>
    </Layout>
  );
};

export default Home;
